### PR TITLE
Helpful file additions

### PR DESCRIPTION
**Pull request by toadkicker**
- [x] Add requirements.txt for pip/easy_install users

- [x] Add gitignore for pycharm users

- [x] formatting on ethdrain.py

- [x] added python-version file for pyenv/virtualenv users

### CODE REVIEW

**Comment by toadkicker** [comment]
Feel free to cherry-pick

**Comment by vkobel** [comment]
Thanks! 
Just wondering: why 2 new lines between functions? Is it a python-specific coding style?

**Comment by toadkicker** [comment]
https://www.python.org/dev/peps/pep-0008/#blank-lines

**Comment by vkobel** [comment]
👍

**Pull request merged**
